dubbo:
  registry:
    address: zookeeper://single-zookeeper:2181

spring:
  datasource:
    url: jdbc:mysql://mysql-57:3306/haitaotao?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: redis
    port: 6379