dubbo:
  registry:
    address: zookeeper://localhost:2181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haitaotao?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: localhost
    port: 6379