server:
  port: 8083
logging:
  level:
    com.haitaotao: debug

dubbo:
  application:
    name: haitaotao-admin-api
    qos-enable: false
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false

minio:
  bucketName: haitaotao
  accessKey: admin
  secretKey: admin123456
  endpoint: http://localhost:9000