version: '3'
services:
  single-zookeeper:
    image: zookeeper:latest
    container_name: single-zookeeper
    ports:
      - 2181:2181
  mysql-57:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=haitaotao
      - TZ=Asia/Shanghai
    ports:
    - 3308:3306
  haitaotao-service:
    image: haitaotao-service:latest
    container_name: haitaotao-service
    ports:
      - 20880:20880
    depends_on:
      - single-zookeeper
      - mysql-57
  haitaotao-admin-api:
    image: haitaotao-admin-api:latest
    container_name: haitaotao-admin-api
    ports:
    - 8083:8083
  dubbo-admin:
    image: chenchuxin/dubbo-admin:latest
    container_name: dubbo-admin
    environment:
      - dubbo.registry.address=zookeeper://single-zookeeper:2181
      - dubbo.admin.root.password=root
      - dubbo.admin.guest.password=guest
    ports:
      - 8080:8080
    depends_on:
      - single-zookeeper
#  apache-dubbo-admin:
#    image: apache/dubbo-admin:latest
#    container_name: apache-dubbo-admin
#    depends_on:
#      - single-zookeeper
#    environment:
#      - admin.registry.address=zookeeper://single-zookeeper:2181
#      - admin.config-center=zookeeper://single-zookeeper:2181
#      - admin.metadata-report.address=zookeeper://single-zookeeper:2181
#    ports:
#      - 8078:8080
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123456
    ports:
      - 9000:9000
    command: server /data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379